title: Yining Nie
logo: /assets/img/Nie.jpg

url: "https://yiningnie.github.io"
email: "yining.nie@sjsu.edu"

description: Assistant Professor<br>[Linguistics and Language Development](https://www.sjsu.edu/linguistics/)<br>San José State University<br>yining.nie(æt)sjsu.edu

theme: jekyll-theme-minimal

github: [metadata]
