title: Yining Nie
logo: /assets/img/Nie.jpg

url: "https://yiningnie.github.io"
email: "yining.nie@sjsu.edu"

description: Yining Nie [niː]<br>Assistant Professor<br><a href="https://www.sjsu.edu/linguistics/">Department of Linguistics and Language Development</a><br>San José State University<br>yining.nie(æt)sjsu.edu

theme: jekyll-theme-minimal

github: [metadata]
