title: Yining Nie [niː]
logo: /assets/img/Nie.jpg

url: "https://yiningnie.github.io"
email: "yining.nie@sjsu.edu"

description: Assistant Professor, SJSU Linguistics

theme: jekyll-theme-minimal

github: [metadata]

plugins:
- jekyll-redirect-from